version: '3.7'

services:
  adoteumamanha-vuefrontend:
    image: adote-um-amanha/frontenduat:latest
    ports:
      - "5021:80"
    networks:
      - frontend

networks:
  frontend:
    external: true
    driver: bridge
