version: '3.7'

services:
  adoteumamanha-vuefrontend:
    image: adote-um-amanha/vuefrontend:latest
    ports:
      - "80:80"
    networks:
      - frontend

networks:
  frontend:
    external: true
    driver: bridge
